### ISSUE TITLE
Titolo errato nel tornare indietro dal document viewer.

### ISSUE THREAD

**Issue by n4y0n** [ITISEnricoFermi/archivio-digitale-client#6]
### Passaggi 
- Apri un qualunque documento dalla dashboard cliccando visualizza
- Clicca torna indietro
- Garda il titolo della pagina

Related image:
![Img](https://user-images.githubusercontent.com/13003649/53869433-8a863000-3ff8-11e9-8f22-47951a8c7b74.jpg)

**Comment by Richard1984** [comment]
Tu non stai bene 😆

**Comment by Richard1984** [comment]
Risolto.
